<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateChildrenWithSpecialNeedsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('children_with_special_needs', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('statistic_id');

            $table->smallInteger('blindness_cl1_b')->unsigned();
            $table->smallInteger('blindness_cl1_g')->unsigned();
            $table->smallInteger('blindness_cl2_b')->unsigned();
            $table->smallInteger('blindness_cl2_g')->unsigned();
            $table->smallInteger('blindness_cl3_b')->unsigned();
            $table->smallInteger('blindness_cl3_g')->unsigned();
            $table->smallInteger('blindness_cl4_b')->unsigned();
            $table->smallInteger('blindness_cl4_g')->unsigned();
            $table->smallInteger('blindness_cl5_b')->unsigned();
            $table->smallInteger('blindness_cl5_g')->unsigned();
            $table->smallInteger('blindness_cl6_b')->unsigned();
            $table->smallInteger('blindness_cl6_g')->unsigned();
            $table->smallInteger('blindness_cl7_b')->unsigned();
            $table->smallInteger('blindness_cl7_g')->unsigned();
            $table->smallInteger('blindness_cl8_b')->unsigned();
            $table->smallInteger('blindness_cl8_g')->unsigned();
            $table->smallInteger('blindness_cl9_b')->unsigned();
            $table->smallInteger('blindness_cl9_g')->unsigned();
            $table->smallInteger('blindness_cl10_b')->unsigned();
            $table->smallInteger('blindness_cl10_g')->unsigned();
            $table->smallInteger('blindness_cl11_b')->unsigned();
            $table->smallInteger('blindness_cl11_g')->unsigned();
            $table->smallInteger('blindness_cl12_b')->unsigned();
            $table->smallInteger('blindness_cl12_g')->unsigned();

            $table->smallInteger('low_vision_cl1_b')->unsigned();
            $table->smallInteger('low_vision_cl1_g')->unsigned();
            $table->smallInteger('low_vision_cl2_b')->unsigned();
            $table->smallInteger('low_vision_cl2_g')->unsigned();
            $table->smallInteger('low_vision_cl3_b')->unsigned();
            $table->smallInteger('low_vision_cl3_g')->unsigned();
            $table->smallInteger('low_vision_cl4_b')->unsigned();
            $table->smallInteger('low_vision_cl4_g')->unsigned();
            $table->smallInteger('low_vision_cl5_b')->unsigned();
            $table->smallInteger('low_vision_cl5_g')->unsigned();
            $table->smallInteger('low_vision_cl6_b')->unsigned();
            $table->smallInteger('low_vision_cl6_g')->unsigned();
            $table->smallInteger('low_vision_cl7_b')->unsigned();
            $table->smallInteger('low_vision_cl7_g')->unsigned();
            $table->smallInteger('low_vision_cl8_b')->unsigned();
            $table->smallInteger('low_vision_cl8_g')->unsigned();
            $table->smallInteger('low_vision_cl9_b')->unsigned();
            $table->smallInteger('low_vision_cl9_g')->unsigned();
            $table->smallInteger('low_vision_cl10_b')->unsigned();
            $table->smallInteger('low_vision_cl10_g')->unsigned();
            $table->smallInteger('low_vision_cl11_b')->unsigned();
            $table->smallInteger('low_vision_cl11_g')->unsigned();
            $table->smallInteger('low_vision_cl12_b')->unsigned();
            $table->smallInteger('low_vision_cl12_g')->unsigned();

            $table->smallInteger('hearing_impairment_cl1_b')->unsigned();
            $table->smallInteger('hearing_impairment_cl1_g')->unsigned();
            $table->smallInteger('hearing_impairment_cl2_b')->unsigned();
            $table->smallInteger('hearing_impairment_cl2_g')->unsigned();
            $table->smallInteger('hearing_impairment_cl3_b')->unsigned();
            $table->smallInteger('hearing_impairment_cl3_g')->unsigned();
            $table->smallInteger('hearing_impairment_cl4_b')->unsigned();
            $table->smallInteger('hearing_impairment_cl4_g')->unsigned();
            $table->smallInteger('hearing_impairment_cl5_b')->unsigned();
            $table->smallInteger('hearing_impairment_cl5_g')->unsigned();
            $table->smallInteger('hearing_impairment_cl6_b')->unsigned();
            $table->smallInteger('hearing_impairment_cl6_g')->unsigned();
            $table->smallInteger('hearing_impairment_cl7_b')->unsigned();
            $table->smallInteger('hearing_impairment_cl7_g')->unsigned();
            $table->smallInteger('hearing_impairment_cl8_b')->unsigned();
            $table->smallInteger('hearing_impairment_cl8_g')->unsigned();
            $table->smallInteger('hearing_impairment_cl9_b')->unsigned();
            $table->smallInteger('hearing_impairment_cl9_g')->unsigned();
            $table->smallInteger('hearing_impairment_cl10_b')->unsigned();
            $table->smallInteger('hearing_impairment_cl10_g')->unsigned();
            $table->smallInteger('hearing_impairment_cl11_b')->unsigned();
            $table->smallInteger('hearing_impairment_cl11_g')->unsigned();
            $table->smallInteger('hearing_impairment_cl12_b')->unsigned();
            $table->smallInteger('hearing_impairment_cl12_g')->unsigned();

            $table->smallInteger('speech_impairment_cl1_b')->unsigned();
            $table->smallInteger('speech_impairment_cl1_g')->unsigned();
            $table->smallInteger('speech_impairment_cl2_b')->unsigned();
            $table->smallInteger('speech_impairment_cl2_g')->unsigned();
            $table->smallInteger('speech_impairment_cl3_b')->unsigned();
            $table->smallInteger('speech_impairment_cl3_g')->unsigned();
            $table->smallInteger('speech_impairment_cl4_b')->unsigned();
            $table->smallInteger('speech_impairment_cl4_g')->unsigned();
            $table->smallInteger('speech_impairment_cl5_b')->unsigned();
            $table->smallInteger('speech_impairment_cl5_g')->unsigned();
            $table->smallInteger('speech_impairment_cl6_b')->unsigned();
            $table->smallInteger('speech_impairment_cl6_g')->unsigned();
            $table->smallInteger('speech_impairment_cl7_b')->unsigned();
            $table->smallInteger('speech_impairment_cl7_g')->unsigned();
            $table->smallInteger('speech_impairment_cl8_b')->unsigned();
            $table->smallInteger('speech_impairment_cl8_g')->unsigned();
            $table->smallInteger('speech_impairment_cl9_b')->unsigned();
            $table->smallInteger('speech_impairment_cl9_g')->unsigned();
            $table->smallInteger('speech_impairment_cl10_b')->unsigned();
            $table->smallInteger('speech_impairment_cl10_g')->unsigned();
            $table->smallInteger('speech_impairment_cl11_b')->unsigned();
            $table->smallInteger('speech_impairment_cl11_g')->unsigned();
            $table->smallInteger('speech_impairment_cl12_b')->unsigned();
            $table->smallInteger('speech_impairment_cl12_g')->unsigned();

            $table->smallInteger('locomotor_impairment_cl1_b')->unsigned();
            $table->smallInteger('locomotor_impairment_cl1_g')->unsigned();
            $table->smallInteger('locomotor_impairment_cl2_b')->unsigned();
            $table->smallInteger('locomotor_impairment_cl2_g')->unsigned();
            $table->smallInteger('locomotor_impairment_cl3_b')->unsigned();
            $table->smallInteger('locomotor_impairment_cl3_g')->unsigned();
            $table->smallInteger('locomotor_impairment_cl4_b')->unsigned();
            $table->smallInteger('locomotor_impairment_cl4_g')->unsigned();
            $table->smallInteger('locomotor_impairment_cl5_b')->unsigned();
            $table->smallInteger('locomotor_impairment_cl5_g')->unsigned();
            $table->smallInteger('locomotor_impairment_cl6_b')->unsigned();
            $table->smallInteger('locomotor_impairment_cl6_g')->unsigned();
            $table->smallInteger('locomotor_impairment_cl7_b')->unsigned();
            $table->smallInteger('locomotor_impairment_cl7_g')->unsigned();
            $table->smallInteger('locomotor_impairment_cl8_b')->unsigned();
            $table->smallInteger('locomotor_impairment_cl8_g')->unsigned();
            $table->smallInteger('locomotor_impairment_cl9_b')->unsigned();
            $table->smallInteger('locomotor_impairment_cl9_g')->unsigned();
            $table->smallInteger('locomotor_impairment_cl10_b')->unsigned();
            $table->smallInteger('locomotor_impairment_cl10_g')->unsigned();
            $table->smallInteger('locomotor_impairment_cl11_b')->unsigned();
            $table->smallInteger('locomotor_impairment_cl11_g')->unsigned();
            $table->smallInteger('locomotor_impairment_cl12_b')->unsigned();
            $table->smallInteger('locomotor_impairment_cl12_g')->unsigned();

            $table->smallInteger('mental_retardation_cl1_b')->unsigned();
            $table->smallInteger('mental_retardation_cl1_g')->unsigned();
            $table->smallInteger('mental_retardation_cl2_b')->unsigned();
            $table->smallInteger('mental_retardation_cl2_g')->unsigned();
            $table->smallInteger('mental_retardation_cl3_b')->unsigned();
            $table->smallInteger('mental_retardation_cl3_g')->unsigned();
            $table->smallInteger('mental_retardation_cl4_b')->unsigned();
            $table->smallInteger('mental_retardation_cl4_g')->unsigned();
            $table->smallInteger('mental_retardation_cl5_b')->unsigned();
            $table->smallInteger('mental_retardation_cl5_g')->unsigned();
            $table->smallInteger('mental_retardation_cl6_b')->unsigned();
            $table->smallInteger('mental_retardation_cl6_g')->unsigned();
            $table->smallInteger('mental_retardation_cl7_b')->unsigned();
            $table->smallInteger('mental_retardation_cl7_g')->unsigned();
            $table->smallInteger('mental_retardation_cl8_b')->unsigned();
            $table->smallInteger('mental_retardation_cl8_g')->unsigned();
            $table->smallInteger('mental_retardation_cl9_b')->unsigned();
            $table->smallInteger('mental_retardation_cl9_g')->unsigned();
            $table->smallInteger('mental_retardation_cl10_b')->unsigned();
            $table->smallInteger('mental_retardation_cl10_g')->unsigned();
            $table->smallInteger('mental_retardation_cl11_b')->unsigned();
            $table->smallInteger('mental_retardation_cl11_g')->unsigned();
            $table->smallInteger('mental_retardation_cl12_b')->unsigned();
            $table->smallInteger('mental_retardation_cl12_g')->unsigned();

            $table->smallInteger('learning_disability_cl1_b')->unsigned();
            $table->smallInteger('learning_disability_cl1_g')->unsigned();
            $table->smallInteger('learning_disability_cl2_b')->unsigned();
            $table->smallInteger('learning_disability_cl2_g')->unsigned();
            $table->smallInteger('learning_disability_cl3_b')->unsigned();
            $table->smallInteger('learning_disability_cl3_g')->unsigned();
            $table->smallInteger('learning_disability_cl4_b')->unsigned();
            $table->smallInteger('learning_disability_cl4_g')->unsigned();
            $table->smallInteger('learning_disability_cl5_b')->unsigned();
            $table->smallInteger('learning_disability_cl5_g')->unsigned();
            $table->smallInteger('learning_disability_cl6_b')->unsigned();
            $table->smallInteger('learning_disability_cl6_g')->unsigned();
            $table->smallInteger('learning_disability_cl7_b')->unsigned();
            $table->smallInteger('learning_disability_cl7_g')->unsigned();
            $table->smallInteger('learning_disability_cl8_b')->unsigned();
            $table->smallInteger('learning_disability_cl8_g')->unsigned();
            $table->smallInteger('learning_disability_cl9_b')->unsigned();
            $table->smallInteger('learning_disability_cl9_g')->unsigned();
            $table->smallInteger('learning_disability_cl10_b')->unsigned();
            $table->smallInteger('learning_disability_cl10_g')->unsigned();
            $table->smallInteger('learning_disability_cl11_b')->unsigned();
            $table->smallInteger('learning_disability_cl11_g')->unsigned();
            $table->smallInteger('learning_disability_cl12_b')->unsigned();
            $table->smallInteger('learning_disability_cl12_g')->unsigned();

            $table->smallInteger('cerebaral_palsy_cl1_b')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl1_g')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl2_b')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl2_g')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl3_b')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl3_g')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl4_b')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl4_g')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl5_b')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl5_g')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl6_b')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl6_g')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl7_b')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl7_g')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl8_b')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl8_g')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl9_b')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl9_g')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl10_b')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl10_g')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl11_b')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl11_g')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl12_b')->unsigned();
            $table->smallInteger('cerebaral_palsy_cl12_g')->unsigned();

            $table->smallInteger('autism_cl1_b')->unsigned();
            $table->smallInteger('autism_cl1_g')->unsigned();
            $table->smallInteger('autism_cl2_b')->unsigned();
            $table->smallInteger('autism_cl2_g')->unsigned();
            $table->smallInteger('autism_cl3_b')->unsigned();
            $table->smallInteger('autism_cl3_g')->unsigned();
            $table->smallInteger('autism_cl4_b')->unsigned();
            $table->smallInteger('autism_cl4_g')->unsigned();
            $table->smallInteger('autism_cl5_b')->unsigned();
            $table->smallInteger('autism_cl5_g')->unsigned();
            $table->smallInteger('autism_cl6_b')->unsigned();
            $table->smallInteger('autism_cl6_g')->unsigned();
            $table->smallInteger('autism_cl7_b')->unsigned();
            $table->smallInteger('autism_cl7_g')->unsigned();
            $table->smallInteger('autism_cl8_b')->unsigned();
            $table->smallInteger('autism_cl8_g')->unsigned();
            $table->smallInteger('autism_cl9_b')->unsigned();
            $table->smallInteger('autism_cl9_g')->unsigned();
            $table->smallInteger('autism_cl10_b')->unsigned();
            $table->smallInteger('autism_cl10_g')->unsigned();
            $table->smallInteger('autism_cl11_b')->unsigned();
            $table->smallInteger('autism_cl11_g')->unsigned();
            $table->smallInteger('autism_cl12_b')->unsigned();
            $table->smallInteger('autism_cl12_g')->unsigned();

            $table->smallInteger('multiple_disability_cl1_b')->unsigned();
            $table->smallInteger('multiple_disability_cl1_g')->unsigned();
            $table->smallInteger('multiple_disability_cl2_b')->unsigned();
            $table->smallInteger('multiple_disability_cl2_g')->unsigned();
            $table->smallInteger('multiple_disability_cl3_b')->unsigned();
            $table->smallInteger('multiple_disability_cl3_g')->unsigned();
            $table->smallInteger('multiple_disability_cl4_b')->unsigned();
            $table->smallInteger('multiple_disability_cl4_g')->unsigned();
            $table->smallInteger('multiple_disability_cl5_b')->unsigned();
            $table->smallInteger('multiple_disability_cl5_g')->unsigned();
            $table->smallInteger('multiple_disability_cl6_b')->unsigned();
            $table->smallInteger('multiple_disability_cl6_g')->unsigned();
            $table->smallInteger('multiple_disability_cl7_b')->unsigned();
            $table->smallInteger('multiple_disability_cl7_g')->unsigned();
            $table->smallInteger('multiple_disability_cl8_b')->unsigned();
            $table->smallInteger('multiple_disability_cl8_g')->unsigned();
            $table->smallInteger('multiple_disability_cl9_b')->unsigned();
            $table->smallInteger('multiple_disability_cl9_g')->unsigned();
            $table->smallInteger('multiple_disability_cl10_b')->unsigned();
            $table->smallInteger('multiple_disability_cl10_g')->unsigned();
            $table->smallInteger('multiple_disability_cl11_b')->unsigned();
            $table->smallInteger('multiple_disability_cl11_g')->unsigned();
            $table->smallInteger('multiple_disability_cl12_b')->unsigned();
            $table->smallInteger('multiple_disability_cl12_g')->unsigned();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('children_with_special_needs');
    }
}
